name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm install --package-lock-only  # Regenerate package-lock.json with the current npm version
    - run: npm ci  # Clean install based on the updated package-lock.json
    
    - run: npm run build  # Build the project before serving
    - run: npm run serve &  # Start the server in the background
      env:
        NODE_ENV: development  # Set environment variable if needed

    - run: sleep 10  # Allow some time for the server to start before running tests
    - run: npm test  # Run tests after the server is up
